-- Adicionar colunas de filtro na tabela properties
ALTER TABLE properties ADD COLUMN IF NOT EXISTS mobiliado BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE properties ADD COLUMN IF NOT EXISTS permite_pets BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE properties ADD COLUMN IF NOT EXISTS permite_fumantes BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE properties ADD COLUMN IF NOT EXISTS inclui_alimentacao BOOLEAN NOT NULL DEFAULT FALSE;
